SDT-TIME-STAMP-1.0
1545380089 C:\Documents and Settings\Administrator\桌面\Selection\Selection\SelectiveARQ.ssy
1545380089 C:\Documents and Settings\Administrator\桌面\Selection\Selection\DataLink_1.sbk
1545380089 C:\Documents and Settings\Administrator\桌面\Selection\Selection\P_1
1545380089 C:\Documents and Settings\Administrator\桌面\Selection\Selection\between.spd
1545380089 C:\Documents and Settings\Administrator\桌面\Selection\Selection\DataLink_2.sbk
1545380089 C:\Documents and Settings\Administrator\桌面\Selection\Selection\P_2
1545380089 C:\Documents and Settings\Administrator\桌面\Selection\Selection\between1.spd
