
package buptsse;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StringOperationService", targetNamespace = "http://buptsse/", wsdlLocation = "http://localhost:8080/WebServiceProject/StringOperationPort?WSDL")
public class StringOperationService
    extends Service
{

    private final static URL STRINGOPERATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException STRINGOPERATIONSERVICE_EXCEPTION;
    private final static QName STRINGOPERATIONSERVICE_QNAME = new QName("http://buptsse/", "StringOperationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WebServiceProject/StringOperationPort?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STRINGOPERATIONSERVICE_WSDL_LOCATION = url;
        STRINGOPERATIONSERVICE_EXCEPTION = e;
    }

    public StringOperationService() {
        super(__getWsdlLocation(), STRINGOPERATIONSERVICE_QNAME);
    }

    public StringOperationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STRINGOPERATIONSERVICE_QNAME, features);
    }

    public StringOperationService(URL wsdlLocation) {
        super(wsdlLocation, STRINGOPERATIONSERVICE_QNAME);
    }

    public StringOperationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STRINGOPERATIONSERVICE_QNAME, features);
    }

    public StringOperationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StringOperationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StringOperationDelegate
     */
    @WebEndpoint(name = "StringOperationPort")
    public StringOperationDelegate getStringOperationPort() {
        return super.getPort(new QName("http://buptsse/", "StringOperationPort"), StringOperationDelegate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StringOperationDelegate
     */
    @WebEndpoint(name = "StringOperationPort")
    public StringOperationDelegate getStringOperationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://buptsse/", "StringOperationPort"), StringOperationDelegate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STRINGOPERATIONSERVICE_EXCEPTION!= null) {
            throw STRINGOPERATIONSERVICE_EXCEPTION;
        }
        return STRINGOPERATIONSERVICE_WSDL_LOCATION;
    }

}
