
/* Program generated by Cbasic 4.3.0  */
#define XSCT_CBASIC

#define SCT_VERSION_4_3
#include "scttypes.h"
#ifdef XINCLUDE_HS_FILE
#include "GoBackN.hs"
#endif
XSYSTEMVARS
#ifdef XCTRACE
static char  xFileName[] = "D:\\GoBackN\\project\\project\\GoBackN.c";
#endif

/*************************************************************************
**                SECTION Types and Forward references                  **
*************************************************************************/

/*****
* SYSTEM GoBackN
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy,4,1)
******/
extern XCONST struct xSystemIdStruct ySysR_z_GoBackN;

/*****
* NEWTYPE Packet  (TYPE section)
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),155(55,25),1,9)
******/
extern tSDLStructInfo ySDL_z9_Packet;
typedef struct z9_Packet_s {
    SDL_Charstring  Data;
} z9_Packet;

/*****
* NEWTYPE DataFrame  (TYPE section)
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),155(55,25),5,9)
******/
extern tSDLStructInfo ySDL_zA_DataFrame;
typedef struct zA_DataFrame_s {
    z9_Packet  Info;
    SDL_Integer  seq;
    SDL_Integer  Flag;
} zA_DataFrame;

/*****
* NEWTYPE AckFrame  (TYPE section)
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),155(55,25),11,9)
******/
extern tSDLStructInfo ySDL_zB_AckFrame;
typedef struct zB_AckFrame_s {
    SDL_Integer  Ack;
    SDL_Integer  seq;
} zB_AckFrame;

/*****
* NEWTYPE Packet  (HEADING section)
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),155(55,25),1,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z9_Packet;
#define ySrtN_z9_Packet  (&ySrtR_z9_Packet)
#endif

#define yAss_z9_Packet(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z9_Packet)
#define yAssF_z9_Packet(V,E,A)  yAss_z9_Packet(&(V),E,A)
#define yEq_z9_Packet(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z9_Packet)
#define yEqF_z9_Packet(Expr1,Expr2)  yEq_z9_Packet(Expr1,Expr2)
#define yNEqF_z9_Packet(Expr1,Expr2)  ( ! yEq_z9_Packet(Expr1,Expr2) )
#define yFree_z9_Packet(P) GenericFreeSort((void **)P, (tSDLTypeInfo *)&ySDL_z9_Packet)
#ifndef ANY_z9_Packet
#define ANY_z9_Packet(R) (z9_Packet *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z9_Packet)
#endif
#define z93_copy(P)  P

/*****
* NEWTYPE DataFrame  (HEADING section)
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),155(55,25),5,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_zA_DataFrame;
#define ySrtN_zA_DataFrame  (&ySrtR_zA_DataFrame)
#endif

#define yAss_zA_DataFrame(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_zA_DataFrame)
#define yAssF_zA_DataFrame(V,E,A)  yAss_zA_DataFrame(&(V),E,A)
#define yEq_zA_DataFrame(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_zA_DataFrame)
#define yEqF_zA_DataFrame(Expr1,Expr2)  yEq_zA_DataFrame(Expr1,Expr2)
#define yNEqF_zA_DataFrame(Expr1,Expr2)  ( ! yEq_zA_DataFrame(Expr1,Expr2) )
#define yFree_zA_DataFrame(P) GenericFreeSort((void **)P, (tSDLTypeInfo *)&ySDL_zA_DataFrame)
#ifndef ANY_zA_DataFrame
#define ANY_zA_DataFrame(R) (zA_DataFrame *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_zA_DataFrame)
#endif
#define zA3_copy(P)  P

/*****
* NEWTYPE AckFrame  (HEADING section)
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),155(55,25),11,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_zB_AckFrame;
#define ySrtN_zB_AckFrame  (&ySrtR_zB_AckFrame)
#endif

#define yAssF_zB_AckFrame(V,E,A)  V = *(zB_AckFrame *)(E)
#define yEq_zB_AckFrame(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_zB_AckFrame)
#define yEqF_zB_AckFrame(Expr1,Expr2)  yEq_zB_AckFrame(Expr1,Expr2)
#define yNEqF_zB_AckFrame(Expr1,Expr2)  ( ! yEq_zB_AckFrame(Expr1,Expr2) )
#ifndef ANY_zB_AckFrame
#define ANY_zB_AckFrame(R) (zB_AckFrame *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_zB_AckFrame)
#endif
#define zB3_copy(P)  P

/*****
* BLOCK DataLink1
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1,4,1)
******/
extern XCONST struct xBlockIdStruct yBloR_z0_DataLink1;

/*****
* NEWTYPE bufferType  (TYPE section)
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),122(35,10),1,9)
******/
extern tSDLGArrayInfo ySDL_z022_bufferType;

typedef struct z022_bufferType_ystruct * z022_bufferType_yptr;
typedef struct z022_bufferType_ystruct {
  z022_bufferType_yptr Suc;
  SDL_Integer Index;
  z9_Packet Data;
} z022_bufferType_yrec;
typedef struct {
  z022_bufferType_yptr First;
  z022_bufferType_yptr Last;
  int IsAssigned;
  z9_Packet Data;
} z022_bufferType;

/*****
* NEWTYPE bufferType  (HEADING section)
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),122(35,10),1,9)
******/
#ifndef XOPTSORT
extern XCONST struct xSortIdStruct ySrtR_z022_bufferType;
#define ySrtN_z022_bufferType  (&ySrtR_z022_bufferType)
#endif

#define yAss_z022_bufferType(Addr,Expr,AssName) (void)GenericAssignSort(Addr,Expr,AssName,(tSDLTypeInfo *)&ySDL_z022_bufferType)
#define yAssF_z022_bufferType(V,E,A)  yAss_z022_bufferType(&(V),E,A)
#define yEq_z022_bufferType(Expr1,Expr2) GenericEqualSort((void *)Expr1,(void *)Expr2,(tSDLTypeInfo *)&ySDL_z022_bufferType)
#define yEqF_z022_bufferType(Expr1,Expr2)  yEq_z022_bufferType(Expr1,Expr2)
#define yNEqF_z022_bufferType(Expr1,Expr2)  ( ! yEq_z022_bufferType(Expr1,Expr2) )
#define yFree_z022_bufferType(P) GenericFreeSort((void **)P, (tSDLTypeInfo *)&ySDL_z022_bufferType)
#define yExtr_z022_bufferType(V1,V2) ((z9_Packet *)GenGArray_Extract((xGArray_Type *)V1,V2,&ySDL_z022_bufferType))
#define yAddr_z022_bufferType(V1,V2) ((z9_Packet *)GenGArray_Modify((xGArray_Type *)V1,V2,&ySDL_z022_bufferType))
#ifndef ANY_z022_bufferType
#define ANY_z022_bufferType(R) (z022_bufferType *)GenericAnySort(R, (tSDLTypeInfo *)&ySDL_z022_bufferType)
#endif
#define z0226_copy(P)  P

/*****
* PROCESS p1
* <<SYSTEM GoBackN/BLOCK DataLink1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr,4,1)
******/
extern XCONST XSIGTYPE yPrsS_z02_p1[];
extern XCONST xStateIdNode yPrsT_z02_p1[];
extern XCONST struct xPrsIdStruct yPrsR_z02_p1;
#define yPrsN_z02_p1  (&yPrsR_z02_p1)
#ifdef XCOVERAGE
extern long int yPrsC_z02_p1[];
#endif
YPAD_PROTOTYPE(yPAD_z02_p1)
extern XCONST struct xSignalIdStruct ySigR_z02_p1;
#define ySigN_z02_p1  (&ySigR_z02_p1)
typedef struct {
    SIGNAL_VARS
    STARTUP_VARS
} yPDef_z02_p1;
typedef yPDef_z02_p1  *yPDP_z02_p1;
XPROCESSDEF_H(p1,"p1",z02_p1,yPAD_z02_p1,yVDef_z02_p1)
#ifndef XOPTCHAN
extern XCONST xIdNode yPrsO_z02_p1[];
#endif
#ifdef XBREAKBEFORE
#define ySym_z02_p1  37
extern char * yRef_z02_p1 (int, xSymbolType *);
#endif
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),2,1) */
    SDL_Integer z025_next_frame_to_send;
                /* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),3,1) */
    SDL_Integer z026_ack_expected;
                /* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),4,1) */
    SDL_Integer z027_next_frame_expected;
                /* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),5,1) */
    SDL_Integer z028_frame_to_dl2;
                /* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),6,1) */
    SDL_Integer z029_nbuffered;
                /* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),7,1) */
    zB_AckFrame z02A_r;
                /* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),8,1) */
    zA_DataFrame z02B_s;
                /* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),9,1) */
    SDL_Integer z02C_a;
                /* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),10,1) */
    SDL_Integer z02D_X;
                /* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),11,5) */
    z022_bufferType z02E_buffer;
                /* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),12,7) */
    DEF_TIMER_VAR_PARA(yTim_T)
} yVDef_z02_p1;
typedef yVDef_z02_p1  *yVDP_z02_p1;
extern void yFree_z02_p1 (void *);

/*****
* STATE Wait
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),137(85,60),1,1)
******/
#define z023_Wait  1
#ifndef XNOENABCONDFUNC
extern xInputAction yEnab_z023_Wait (XSIGTYPE, void *);
#endif
extern XCONST struct xStateIdStruct yStaR_z023_Wait;
#define yStaN_z023_Wait  (&yStaR_z023_Wait)

/*****
* TIMER T
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),12,7)
******/
extern XCONST struct xSignalIdStruct ySigR_z024_T;
#define ySigN_z024_T  (&ySigR_z024_T)
typedef struct {
    TIMER_VARS
    SDL_Integer  Param1;
} yPDef_z024_T;
typedef yPDef_z024_T  *yPDP_z024_T;
#ifndef XNOEQTIMERFUNC
extern xbool yEqT_z024_T (void *, void *);
#endif

/*****
* DCL next_frame_to_send
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),2,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z025_next_frame_to_send;
#endif

/*****
* DCL ack_expected
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),3,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z026_ack_expected;
#endif

/*****
* DCL next_frame_expected
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),4,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z027_next_frame_expected;
#endif

/*****
* DCL frame_to_dl2
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),5,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z028_frame_to_dl2;
#endif

/*****
* DCL nbuffered
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),6,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z029_nbuffered;
#endif

/*****
* DCL r
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),7,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02A_r;
#endif

/*****
* DCL s
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),8,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02B_s;
#endif

/*****
* DCL a
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),9,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02C_a;
#endif

/*****
* DCL X
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),10,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02D_X;
#endif

/*****
* DCL buffer
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),11,5)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z02E_buffer;
#endif

/*****
* SIGNALROUTE N11
* <<SYSTEM GoBackN/BLOCK DataLink1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1(1),119(47,72),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z03_N11[];
extern XCONST xIdNode yChaOR_z03_N11[];
extern XCONST struct xChannelIdStruct yChaR_z03_N11;
extern XCONST struct xChannelIdStruct yChaRR_z03_N11;
#define yChaN_z03_N11  (&yChaR_z03_N11)
#endif

/*****
* SIGNALROUTE R1
* <<SYSTEM GoBackN/BLOCK DataLink1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1(1),140(142,72),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z04_R1[];
extern XCONST xIdNode yChaOR_z04_R1[];
extern XCONST struct xChannelIdStruct yChaR_z04_R1;
extern XCONST struct xChannelIdStruct yChaRR_z04_R1;
#define yChaN_z04_R1  (&yChaR_z04_R1)
#endif

/*****
* BLOCK DataLink2
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.sbk,4,1)
******/
extern XCONST struct xBlockIdStruct yBloR_z1_DataLink2;

/*****
* PROCESS p2
* <<SYSTEM GoBackN/BLOCK DataLink2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr,4,1)
******/
extern XCONST XSIGTYPE yPrsS_z12_p2[];
extern XCONST xStateIdNode yPrsT_z12_p2[];
extern XCONST struct xPrsIdStruct yPrsR_z12_p2;
#define yPrsN_z12_p2  (&yPrsR_z12_p2)
#ifdef XCOVERAGE
extern long int yPrsC_z12_p2[];
#endif
YPAD_PROTOTYPE(yPAD_z12_p2)
extern XCONST struct xSignalIdStruct ySigR_z12_p2;
#define ySigN_z12_p2  (&ySigR_z12_p2)
typedef struct {
    SIGNAL_VARS
    STARTUP_VARS
} yPDef_z12_p2;
typedef yPDef_z12_p2  *yPDP_z12_p2;
XPROCESSDEF_H(p2,"p2",z12_p2,yPAD_z12_p2,yVDef_z12_p2)
#ifndef XOPTCHAN
extern XCONST xIdNode yPrsO_z12_p2[];
#endif
#ifdef XBREAKBEFORE
#define ySym_z12_p2  11
extern char * yRef_z12_p2 (int, xSymbolType *);
#endif
typedef struct {
    PROCESS_VARS
                /* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),218(35,15),2,1) */
    SDL_Integer z122_frame_expected;
                /* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),218(35,15),3,1) */
    zA_DataFrame z123_r;
                /* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),218(35,15),4,1) */
    zB_AckFrame z124_s;
} yVDef_z12_p2;
typedef yVDef_z12_p2  *yVDP_z12_p2;
extern void yFree_z12_p2 (void *);

/*****
* STATE Wait
* <<SYSTEM GoBackN/BLOCK DataLink2/PROCESS p2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),128(85,35),1,1)
******/
#define z121_Wait  1
extern XCONST struct xStateIdStruct yStaR_z121_Wait;
#define yStaN_z121_Wait  (&yStaR_z121_Wait)

/*****
* DCL frame_expected
* <<SYSTEM GoBackN/BLOCK DataLink2/PROCESS p2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),218(35,15),2,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z122_frame_expected;
#endif

/*****
* DCL r
* <<SYSTEM GoBackN/BLOCK DataLink2/PROCESS p2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),218(35,15),3,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z123_r;
#endif

/*****
* DCL s
* <<SYSTEM GoBackN/BLOCK DataLink2/PROCESS p2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),218(35,15),4,1)
******/
#ifndef XOPTDCL
extern XCONST struct xVarIdStruct yVarR_z124_s;
#endif

/*****
* SIGNALROUTE R2
* <<SYSTEM GoBackN/BLOCK DataLink2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.sbk(1),167(42,82),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z13_R2[];
extern XCONST xIdNode yChaOR_z13_R2[];
extern XCONST struct xChannelIdStruct yChaR_z13_R2;
extern XCONST struct xChannelIdStruct yChaRR_z13_R2;
#define yChaN_z13_R2  (&yChaR_z13_R2)
#endif

/*****
* SIGNALROUTE N21
* <<SYSTEM GoBackN/BLOCK DataLink2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.sbk(1),140(139,82),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z14_N21[];
extern XCONST xIdNode yChaOR_z14_N21[];
extern XCONST struct xChannelIdStruct yChaR_z14_N21;
extern XCONST struct xChannelIdStruct yChaRR_z14_N21;
#define yChaN_z14_N21  (&yChaR_z14_N21)
#endif

/*****
* CHANNEL N1
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),146(30,90),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z2_N1[];
extern XCONST xIdNode yChaOR_z2_N1[];
extern XCONST struct xChannelIdStruct yChaR_z2_N1;
extern XCONST struct xChannelIdStruct yChaRR_z2_N1;
#define yChaN_z2_N1  (&yChaR_z2_N1)
#ifdef XMULTIPLESYSTEMS
extern XCONST xIdNode yConnIn_GoBackN_N1[];
extern XCONST xIdNode yConnOut_GoBackN_N1[];
extern XCONST struct xChannelIdStruct yGateIn_GoBackN_N1;
extern XCONST struct xChannelIdStruct yGateOut_GoBackN_N1;
#endif
#endif

/*****
* CHANNEL R
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),134(100,90),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z3_R[];
extern XCONST xIdNode yChaOR_z3_R[];
extern XCONST struct xChannelIdStruct yChaR_z3_R;
extern XCONST struct xChannelIdStruct yChaRR_z3_R;
#define yChaN_z3_R  (&yChaR_z3_R)
#endif

/*****
* CHANNEL N2
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),137(165,90),1,1)
******/
#ifndef XOPTCHAN
extern XCONST xIdNode yChaO_z4_N2[];
extern XCONST xIdNode yChaOR_z4_N2[];
extern XCONST struct xChannelIdStruct yChaR_z4_N2;
extern XCONST struct xChannelIdStruct yChaRR_z4_N2;
#define yChaN_z4_N2  (&yChaR_z4_N2)
#ifdef XMULTIPLESYSTEMS
extern XCONST xIdNode yConnIn_GoBackN_N2[];
extern XCONST xIdNode yConnOut_GoBackN_N2[];
extern XCONST struct xChannelIdStruct yGateIn_GoBackN_N2;
extern XCONST struct xChannelIdStruct yGateOut_GoBackN_N2;
#endif
#endif

/*****
* SIGNAL DataToDL2
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),158(125,30),2,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z5_DataToDL2;
#define ySigN_z5_DataToDL2  (&ySigR_z5_DataToDL2)
typedef struct {
    SIGNAL_VARS
    zA_DataFrame  Param1;
} yPDef_z5_DataToDL2;
typedef yPDef_z5_DataToDL2  *yPDP_z5_DataToDL2;
#ifdef XFREESIGNALFUNCS
extern void yFree_z5_DataToDL2 (void *SVarP);
#endif

/*****
* SIGNAL FromNW1
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),158(125,30),3,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z6_FromNW1;
#define ySigN_z6_FromNW1  (&ySigR_z6_FromNW1)
typedef struct {
    SIGNAL_VARS
    z9_Packet  Param1;
} yPDef_z6_FromNW1;
typedef yPDef_z6_FromNW1  *yPDP_z6_FromNW1;
#ifdef XFREESIGNALFUNCS
extern void yFree_z6_FromNW1 (void *SVarP);
#endif

/*****
* SIGNAL ToNW2
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),158(125,30),4,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z7_ToNW2;
#define ySigN_z7_ToNW2  (&ySigR_z7_ToNW2)
typedef struct {
    SIGNAL_VARS
    z9_Packet  Param1;
} yPDef_z7_ToNW2;
typedef yPDef_z7_ToNW2  *yPDP_z7_ToNW2;
#ifdef XFREESIGNALFUNCS
extern void yFree_z7_ToNW2 (void *SVarP);
#endif

/*****
* SIGNAL AckToDL1
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),158(125,30),5,1)
******/
extern XCONST struct xSignalIdStruct ySigR_z8_AckToDL1;
#define ySigN_z8_AckToDL1  (&ySigR_z8_AckToDL1)
typedef struct {
    SIGNAL_VARS
    zB_AckFrame  Param1;
} yPDef_z8_AckToDL1;
typedef yPDef_z8_AckToDL1  *yPDP_z8_AckToDL1;

/*************************************************************************
**                #CODE directives, #HEADING sections                   **
*************************************************************************/

/*************************************************************************
**                  #CODE directives, #BODY sections                    **
*************************************************************************/

/*************************************************************************
**                  SECTION Variables and Functions                     **
*************************************************************************/

/*****
* SYSTEM GoBackN
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy,4,1)
******/
XCONST struct xSystemIdStruct ySysR_z_GoBackN = {xSystemEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&xSymbolTableIdRec, "GoBackN" XCOMMON_EXTRAS,
  (xIdNode *)0, (xPrdIdNode *)0, (xSystemIdNode)0 xTrace(-1) xGRTrace(-1)
  xMSCETrace(-1) XSYS_EXTRAS};

/*****
* ENV
******/
#ifndef XMULTIPLESYSTEMS
#ifndef XOPTCHAN
xIdNode yEnvO_env[] = {(xIdNode)&yChaR_z2_N1, (xIdNode)&yChaRR_z4_N2,
  (xIdNode)0  XTRACHANNELLIST};
#endif
#endif

/*****
* NEWTYPE Packet  (BODY section)
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),155(55,25),1,9)
******/

/* *** Packet *** */
static tSDLFieldInfo fSDL_z9_Packet[] = {
  {(tSDLTypeInfo *)&ySDL_SDL_Charstring  T_SDL_Names("Data"),
    xOffsetOf(z9_Packet, Data), 0}
};
tSDLStructInfo ySDL_z9_Packet = {type_SDL_Struct, 7, (xptrint)sizeof(z9_Packet)
  T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE T_SDL_Names("Packet")
  xRaWF((xIdNode)&ySysR_z_GoBackN) xRaWF(&ySrtR_z9_Packet), fSDL_z9_Packet, 1};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z9_Packet = {xSortEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "Packet" XCOMMON_EXTRAS xFreF(0)
  xAssF(yAss_z9_Packet) xEqF(yEq_z9_Packet) xTestF(0),
  (xptrint)sizeof(z9_Packet), xStruct, (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0,
  0 xRaWF((tSDLTypeInfo *)&ySDL_z9_Packet) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_z97_Data = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySrtR_z9_Packet, "Data" XCOMMON_EXTRAS,
  &xSrtR_SDL_Charstring, (tSDLTypeInfo *)&ySDL_SDL_Charstring,
  xOffsetOf(z9_Packet, Data), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE DataFrame  (BODY section)
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),155(55,25),5,9)
******/

/* *** DataFrame *** */
static tSDLFieldInfo fSDL_zA_DataFrame[] = {
  {(tSDLTypeInfo *)&ySDL_z9_Packet  T_SDL_Names("Info"),
    xOffsetOf(zA_DataFrame, Info), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("seq"),
    xOffsetOf(zA_DataFrame, seq), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("Flag"),
    xOffsetOf(zA_DataFrame, Flag), 0}
};
tSDLStructInfo ySDL_zA_DataFrame = {type_SDL_Struct, 7,
  (xptrint)sizeof(zA_DataFrame) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("DataFrame") xRaWF((xIdNode)&ySysR_z_GoBackN)
  xRaWF(&ySrtR_zA_DataFrame), fSDL_zA_DataFrame, 3};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_zA_DataFrame = {xSortEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "DataFrame" XCOMMON_EXTRAS xFreF(0)
  xAssF(yAss_zA_DataFrame) xEqF(yEq_zA_DataFrame) xTestF(0),
  (xptrint)sizeof(zA_DataFrame), xStruct, (xSortIdNode)0, (xSortIdNode)0, 0, 0,
  0, 0 xRaWF((tSDLTypeInfo *)&ySDL_zA_DataFrame) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_zAB_Info = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySrtR_zA_DataFrame, "Info" XCOMMON_EXTRAS,
  &ySrtR_z9_Packet, (tSDLTypeInfo *)&ySDL_z9_Packet, xOffsetOf(zA_DataFrame,
  Info), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_zAC_seq = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySrtR_zA_DataFrame, "seq" XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(zA_DataFrame, seq), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_zAD_Flag = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySrtR_zA_DataFrame, "Flag" XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(zA_DataFrame, Flag), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* NEWTYPE AckFrame  (BODY section)
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),155(55,25),11,9)
******/

/* *** AckFrame *** */
static tSDLFieldInfo fSDL_zB_AckFrame[] = {
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("Ack"),
    xOffsetOf(zB_AckFrame, Ack), 0},
  {(tSDLTypeInfo *)&ySDL_SDL_Integer  T_SDL_Names("seq"),
    xOffsetOf(zB_AckFrame, seq), 0}
};
tSDLStructInfo ySDL_zB_AckFrame = {type_SDL_Struct, 2,
  (xptrint)sizeof(zB_AckFrame) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("AckFrame") xRaWF((xIdNode)&ySysR_z_GoBackN)
  xRaWF(&ySrtR_zB_AckFrame), fSDL_zB_AckFrame, 2};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_zB_AckFrame = {xSortEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "AckFrame" XCOMMON_EXTRAS xFreF(0)
  xAssF(0) xEqF(yEq_zB_AckFrame) xTestF(0), (xptrint)sizeof(zB_AckFrame),
  xStruct, (xSortIdNode)0, (xSortIdNode)0, 0, 0, 0, 0
  xRaWF((tSDLTypeInfo *)&ySDL_zB_AckFrame) XSRT_EXTRAS};
#endif
#ifndef XOPTSTRUCT
/*---------------COMPONENTS----------------*/
static XCONST struct xVarIdStruct yVarR_zB9_Ack = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySrtR_zB_AckFrame, "Ack" XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer, xOffsetOf(zB_AckFrame,
  Ack), (xptrint)0, 0 XVAR_EXTRAS};
static XCONST struct xVarIdStruct yVarR_zBA_seq = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySrtR_zB_AckFrame, "seq" XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer, xOffsetOf(zB_AckFrame,
  seq), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* BLOCK DataLink1
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1,4,1)
******/
XCONST struct xBlockIdStruct yBloR_z0_DataLink1 = {xBlockEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "DataLink1" XCOMMON_EXTRAS,
  (xBlockIdNode)0, (xIdNode *)0, (xPrdIdNode *)0, (xViewListRec *)0,
  (xViewIndexRec *)0, 1 xTrace(-1) xGRTrace(-1) xMSCETrace(-1) xMSCETrace(0)
  XBLO_EXTRAS};
#ifndef XOPTCHAN
XCONST xIdNode yChaO_z2_N1[] = {(xIdNode)&yChaR_z03_N11, (xIdNode)0};
XCONST xIdNode yChaO_z3_R[] = {(xIdNode)&yChaRR_z04_R1, (xIdNode)0};
#endif

/*****
* NEWTYPE bufferType  (BODY section)
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),122(35,10),1,9)
******/

/* *** bufferType *** */
tSDLGArrayInfo ySDL_z022_bufferType = {type_SDL_GArray, 15,
  (xptrint)sizeof(z022_bufferType) T_SDL_OPFUNCS(0) T_SDL_EXTRA_VALUE
  T_SDL_Names("bufferType") xRaWF((xIdNode)&yPrsR_z02_p1)
  xRaWF(&ySrtR_z022_bufferType), (tSDLTypeInfo *)&ySDL_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_z9_Packet, (xptrint)sizeof(z022_bufferType_yrec),
  xOffsetOf(z022_bufferType_yrec, Index), xOffsetOf(
  z022_bufferType_yrec, Data), xOffsetOf(z022_bufferType, Data)};
#ifndef XOPTSORT
XCONST struct xSortIdStruct ySrtR_z022_bufferType = {xSortEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "bufferType" XCOMMON_EXTRAS xFreF(0)
  xAssF(yAss_z022_bufferType) xEqF(yEq_z022_bufferType) xTestF(0),
  (xptrint)sizeof(z022_bufferType), xGArray, &ySrtR_z9_Packet,
  &xSrtR_SDL_Integer, (long int)xOffsetOf(z022_bufferType_yrec, Data),
  (long int)sizeof(z022_bufferType_yrec), (long int)xOffsetOf(
  z022_bufferType_yrec, Index), (long int)xOffsetOf(z022_bufferType, Data)
  xRaWF((tSDLTypeInfo *)&ySDL_z022_bufferType) XSRT_EXTRAS};
#endif

/*****
* PROCESS p1
* <<SYSTEM GoBackN/BLOCK DataLink1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr,4,1)
******/
#ifdef XCOVERAGE
long int yPrsC_z02_p1[ySym_z02_p1+1];
#endif
XCONST XSIGTYPE yPrsS_z02_p1[] = {SIGNAL_NAME(FromNW1, &ySigR_z6_FromNW1),
  SIGNAL_NAME(AckToDL1, &ySigR_z8_AckToDL1), SIGNAL_NAME(T, &ySigR_z024_T),
  (XSIGTYPE)0};
XCONST xStateIdNode yPrsT_z02_p1[] = {&xStartStateIdRec, &yStaR_z023_Wait};
static XPRSNODE yPrsA_z02_p1 = (XPRSNODE)0;
static XPRSNODE yPrsB_z02_p1 = (XPRSNODE)0;
XCONST struct xPrsIdStruct yPrsR_z02_p1 = {xProcessEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&yBloR_z0_DataLink1, "p1" XCOMMON_EXTRAS, yPrsT_z02_p1,
  yPrsS_z02_p1 xService(0) xOptChan(yPrsO_z02_p1), -1 xNrInst(1) xNrInst(1),
  &yPrsB_z02_p1, (xptrint)sizeof(yVDef_z02_p1)
  xPrsPrioPar(xDefaultPrioProcess), &yPrsA_z02_p1 xTrace(-1) xGRTrace(-1)
  xBreakB(yRef_z02_p1) xBreakB(ySym_z02_p1) xBreakB(3) xMSCETrace(-1)
  xCoverage(yPrsC_z02_p1) xCoverage(0) xCoverage(0), yPAD_z02_p1, yFree_z02_p1,
  (xPrsIdNode)0, (xPrdIdNode *)0, (xBlockIdNode)0
  xBreakB("#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr,4,1)")
  xThreadName(0) xThreadName(0) XPRS_EXTRAS(z02_p1)};
static xSignalNode ySigA_z02_p1 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z02_p1 = {xStartUpSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_DataLink1 xIdNames("-") XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z02_p1), &ySigA_z02_p1, 0 xFreS(0)
  SIGCODE(STARTUPSIGNAL)
  xBreakB("#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr,4,1)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
XPROCESSDEF_C(p1,"p1",z02_p1,yPAD_z02_p1,yVDef_z02_p1)
#ifndef XOPTCHAN
XCONST xIdNode yPrsO_z02_p1[] = {(xIdNode)&yChaRR_z03_N11,
  (xIdNode)&yChaR_z04_R1, (xIdNode)0};
#endif
void yFree_z02_p1(void *yVarP)
{
  yFree_z022_bufferType((void **)&((yVDef_z02_p1 *)yVarP)->z02E_buffer);
  yFree_zA_DataFrame((void **)&((yVDef_z02_p1 *)yVarP)->z02B_s);
}

/*+++++
* GR ref function for process p1
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr,4,1)
++++++*/
#ifdef XBREAKBEFORE
extern char * yRef_z02_p1 (int SymbolNo, xSymbolType *SymbolType)
{
  switch (SymbolNo) {
    case 0: *SymbolType = xsStart;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),125(85,15),1)";
    case 1: *SymbolType = xsInput;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),143(20,85),1)";
    case 2: *SymbolType = xsInput;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),197(75,85),1)";
    case 3: *SymbolType = xsInput;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),263(155,85),1)";
    case 4: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),131(85,30),1,1)";
    case 5: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),131(85,30),2,1)";
    case 6: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),131(85,30),3,1)";
    case 7: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),131(85,30),4,1)";
    case 8: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),131(85,30),5,1)";
    case 9: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),131(85,30),6,1)";
    case 10: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),137(85,60),1)";
    case 11: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),155(20,125),1,1)";
    case 12: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),158(20,145),1,1)";
    case 13: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),158(20,145),2,1)";
    case 14: *SymbolType = xsOutput;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),167(20,165),1,1)";
    case 15: *SymbolType = xsSet;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),173(20,180),1,1)";
    case 16: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),179(20,195),1,1)";
    case 17: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),179(20,195),2,1)";
    case 18: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),188(20,215),1)";
    case 19: *SymbolType = xsDecision;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),200(75,105),1,1)";
    case 20: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),227(105,100),1,1)";
    case 21: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),230(105,125),1,1)";
    case 22: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),233(105,140),1,1)";
    case 23: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),233(105,140),2,1)";
    case 24: *SymbolType = xsOutput;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),236(105,155),1,1)";
    case 25: *SymbolType = xsReset;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),239(105,180),1,1)";
    case 26: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),242(105,200),1,1)";
    case 27: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),203(75,125),1,1)";
    case 28: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),206(75,145),1,1)";
    case 29: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),209(75,165),1)";
    case 30: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),269(155,130),1,1)";
    case 31: *SymbolType = xsAssignment2Statement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),269(155,130),2,1)";
    case 32: *SymbolType = xsOutput;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),275(155,155),1,1)";
    case 33: *SymbolType = xsReset;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),278(155,175),1,1)";
    case 34: *SymbolType = xsDecision;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),281(155,195),1,1)";
    case 35: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),287(130,205),1)";
    case 36: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),284(155,215),1,1)";
    case 37: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),266(155,110),1,1)";
    default : *SymbolType = xsNoSuchSymbolType; return "";
  }
}
#endif

/*+++++
* Function for process p1
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr,4,1)
++++++*/
YPAD_FUNCTION(yPAD_z02_p1)
{
  YPAD_YSVARP
  YPAD_YVARP(yVDef_z02_p1)
  YPAD_TEMP_VARS
#ifdef XTRACE
  SDL_Boolean yDcn_SDL_Boolean;
#endif
  YPRSNAME_VAR("p1")

  BEGIN_PAD(yVDef_z02_p1)

  LOOP_LABEL
  switch (yVarP->RestartAddress) {

/*-----
* START
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),125(85,15),1)
------*/
  case 0:
    BEGIN_START_TRANSITION(yPDef_z02_p1)
    XAT_FIRST_SYMBOL(0)
    GenericDefault((void *)&yVarP->z02E_buffer,
      (tSDLTypeInfo *)&ySDL_z022_bufferType);
    INIT_TIMER_VAR_PARA(yTim_T)
    XBETWEEN_SYMBOLS(4, 928)

/*-----
* ASSIGNMENT ack_expected := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),131(85,30),1,1)
------*/
#ifdef XCASELABELS
  case 4:
#endif
    yAssF_SDL_Integer(yVarP->z026_ack_expected, SDL_INTEGER_LIT(0),
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("ack_expected := ", &(yVarP->z026_ack_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("ack_expected := ", &(yVarP->z026_ack_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(5, 947)

/*-----
* ASSIGNMENT next_frame_to_send := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),131(85,30),2,1)
------*/
#ifdef XCASELABELS
  case 5:
#endif
    yAssF_SDL_Integer(yVarP->z025_next_frame_to_send, SDL_INTEGER_LIT(0),
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("next_frame_to_send := ", &(yVarP->z025_next_frame_to_send),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("next_frame_to_send := ", &(yVarP->z025_next_frame_to_send),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(6, 966)

/*-----
* ASSIGNMENT next_frame_expected := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),131(85,30),3,1)
------*/
#ifdef XCASELABELS
  case 6:
#endif
    yAssF_SDL_Integer(yVarP->z027_next_frame_expected, SDL_INTEGER_LIT(0),
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("next_frame_expected := ", &(yVarP->z027_next_frame_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("next_frame_expected := ", &(yVarP->z027_next_frame_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(7, 985)

/*-----
* ASSIGNMENT frame_to_dl2 := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),131(85,30),4,1)
------*/
#ifdef XCASELABELS
  case 7:
#endif
    yAssF_SDL_Integer(yVarP->z028_frame_to_dl2, SDL_INTEGER_LIT(0),
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("frame_to_dl2 := ", &(yVarP->z028_frame_to_dl2),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("frame_to_dl2 := ", &(yVarP->z028_frame_to_dl2),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(8, 1004)

/*-----
* ASSIGNMENT ack_expected := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),131(85,30),5,1)
------*/
#ifdef XCASELABELS
  case 8:
#endif
    yAssF_SDL_Integer(yVarP->z026_ack_expected, SDL_INTEGER_LIT(0),
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("ack_expected := ", &(yVarP->z026_ack_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("ack_expected := ", &(yVarP->z026_ack_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(9, 1023)

/*-----
* ASSIGNMENT nbuffered := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),131(85,30),6,1)
------*/
#ifdef XCASELABELS
  case 9:
#endif
    yAssF_SDL_Integer(yVarP->z029_nbuffered, SDL_INTEGER_LIT(0),
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("nbuffered := ", &(yVarP->z029_nbuffered),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("nbuffered := ", &(yVarP->z029_nbuffered),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_SYMBOLS(10, 1042)

/*-----
* NEXTSTATE Wait
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),137(85,60),1)
------*/
#ifdef XCASELABELS
  case 10:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(Wait, z023_Wait, "Wait")

/*-----
* INPUT FromNW1
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),143(20,85),1)
------*/
  case 1:
    XDEBUG_LABEL(Wait_FromNW1)
    XAT_FIRST_SYMBOL(1)
    XOS_TRACE_INPUT("FromNW1")
#ifdef XVALIDATOR_LIB
    yAssF_z9_Packet((* yAddr_z022_bufferType(&(yVarP->z02E_buffer), &(yVarP->
      z025_next_frame_to_send))), &(((yPDef_z6_FromNW1 *)ySVarP)->Param1),
      XASS_MR_ASS_FR);
#else
    yAssF_z9_Packet((* yAddr_z022_bufferType(&(yVarP->z02E_buffer), &(yVarP->
      z025_next_frame_to_send))), &(((yPDef_z6_FromNW1 *)ySVarP)->Param1),
      XASS_AR_ASS_FR);
#endif
    XBETWEEN_SYMBOLS(11, 1071)

/*-----
* ASSIGNMENT nbuffered := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),155(20,125),1,1)
------*/
#ifdef XCASELABELS
  case 11:
#endif
    yAssF_SDL_Integer(yVarP->z029_nbuffered, xPlus_SDL_Integer(yVarP->
      z029_nbuffered, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("nbuffered := ", &(yVarP->z029_nbuffered),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("nbuffered := ", &(yVarP->z029_nbuffered),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_SYMBOLS(12, 1090)

/*-----
* ASSIGNMENT s... := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),158(20,145),1,1)
------*/
#ifdef XCASELABELS
  case 12:
#endif
    yAssF_z9_Packet(yVarP->z02B_s.Info, yExtr_z022_bufferType(&(yVarP->
      z02E_buffer), &(yVarP->z028_frame_to_dl2)), XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("s... := ", &(yVarP->z02B_s.Info),
      (tSDLTypeInfo *)&ySDL_z9_Packet);
#endif
#ifdef XMSCE
    xMSCEAssign("s... := ", &(yVarP->z02B_s.Info),
      (tSDLTypeInfo *)&ySDL_z9_Packet);
#endif
    XBETWEEN_STMTS(13, 1109)

/*-----
* ASSIGNMENT s... := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),158(20,145),2,1)
------*/
#ifdef XCASELABELS
  case 13:
#endif
    yAssF_SDL_Integer(yVarP->z02B_s.seq, yVarP->z028_frame_to_dl2,
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("s... := ", &(yVarP->z02B_s.seq),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("s... := ", &(yVarP->z02B_s.seq),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_SYMBOLS(14, 1128)

/*-----
* OUTPUT DataToDL2
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),167(20,165),1,1)
------*/
#ifdef XCASELABELS
  case 14:
#endif
    ALLOC_SIGNAL_PAR(DataToDL2, ySigN_z5_DataToDL2, TO_PROCESS(p2,
      yPrsN_z12_p2), yPDef_z5_DataToDL2)
    SIGNAL_ALLOC_ERROR
    yAssF_zA_DataFrame(((yPDef_z5_DataToDL2 *)OUTSIGNAL_DATA_PTR)->Param1,
      &(yVarP->z02B_s), XASS_MR_ASS_NF);
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, DataToDL2,
      ySigN_z5_DataToDL2, TO_PROCESS(p2, yPrsN_z12_p2),
      sizeof(yPDef_z5_DataToDL2), "DataToDL2")
    SIGNAL_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS(15, 1146)

/*-----
* SET T
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),173(20,180),1,1)
------*/
#ifdef XCASELABELS
  case 15:
#endif
    ALLOC_TIMER_SIGNAL_PAR(T, ySigN_z024_T, yPDef_z024_T)
    TIMER_SIGNAL_ALLOC_ERROR
    yAssF_SDL_Integer(((yPDef_z024_T *)TIMER_DATA_PTR)->Param1, yVarP->
      z028_frame_to_dl2, XASS_MR_ASS_NF);
    SDL_SET_DUR_WITH_PARA(xPlus_SDL_Time(SDL_NOW,
      SDL_DURATION_LIT(50.0, 50, 0)), SDL_DURATION_LIT(50.0, 50, 0), T,
      ySigN_z024_T, yPDef_z024_T, yEqT_z024_T, yTim_T, "T")
    TIMER_SIGNAL_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS(16, 1163)

/*-----
* ASSIGNMENT next_frame_to_send := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),179(20,195),1,1)
------*/
#ifdef XCASELABELS
  case 16:
#endif
    yAssF_SDL_Integer(yVarP->z025_next_frame_to_send, xPlus_SDL_Integer(yVarP->
      z025_next_frame_to_send, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("next_frame_to_send := ", &(yVarP->z025_next_frame_to_send),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("next_frame_to_send := ", &(yVarP->z025_next_frame_to_send),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_STMTS(17, 1182)

/*-----
* ASSIGNMENT frame_to_dl2 := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),179(20,195),2,1)
------*/
#ifdef XCASELABELS
  case 17:
#endif
    yAssF_SDL_Integer(yVarP->z028_frame_to_dl2, xPlus_SDL_Integer(yVarP->
      z028_frame_to_dl2, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("frame_to_dl2 := ", &(yVarP->z028_frame_to_dl2),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("frame_to_dl2 := ", &(yVarP->z028_frame_to_dl2),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_SYMBOLS(18, 1201)

/*-----
* NEXTSTATE Wait
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),188(20,215),1)
------*/
#ifdef XCASELABELS
  case 18:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(Wait, z023_Wait, "Wait")

/*-----
* INPUT AckToDL1
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),197(75,85),1)
------*/
  case 2:
    XDEBUG_LABEL(Wait_AckToDL1)
    XAT_FIRST_SYMBOL(2)
    XOS_TRACE_INPUT("AckToDL1")
    yAssF_zB_AckFrame(yVarP->z02A_r, &(((yPDef_z8_AckToDL1 *)ySVarP)->Param1),
      XASS_AR_ASS_FR);
    XBETWEEN_SYMBOLS(19, 1223)

/*-----
* DECISION
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),200(75,105),1,1)
------*/
#ifdef XCASELABELS
  case 19:
#endif
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yEqF_SDL_Integer(yVarP->z02A_r.Ack,
      yVarP->z026_ack_expected), XASS_MR_ASS_FR);
    xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
    xMSCEDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    if (yDcn_SDL_Boolean) {
#else
    if (yEqF_SDL_Integer(yVarP->z02A_r.Ack, yVarP->z026_ack_expected)) {
#endif
      XBETWEEN_SYMBOLS(27, 1243)

/*-----
* ASSIGNMENT nbuffered := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),203(75,125),1,1)
------*/
#ifdef XCASELABELS
    case 27:
#endif
      yAssF_SDL_Integer(yVarP->z029_nbuffered, xMinus_SDL_Integer(yVarP->
        z029_nbuffered, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("nbuffered := ", &(yVarP->z029_nbuffered),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign("nbuffered := ", &(yVarP->z029_nbuffered),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
      XBETWEEN_SYMBOLS(28, 1262)

/*-----
* ASSIGNMENT ack_expected := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),206(75,145),1,1)
------*/
#ifdef XCASELABELS
    case 28:
#endif
      yAssF_SDL_Integer(yVarP->z026_ack_expected, xPlus_SDL_Integer(yVarP->
        z026_ack_expected, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("ack_expected := ", &(yVarP->z026_ack_expected),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign("ack_expected := ", &(yVarP->z026_ack_expected),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
      XBETWEEN_SYMBOLS(29, 1281)

/*-----
* NEXTSTATE Wait
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),209(75,165),1)
------*/
#ifdef XCASELABELS
    case 29:
#endif
      XAT_LAST_SYMBOL
      SDL_NEXTSTATE(Wait, z023_Wait, "Wait")
    } else {
      XBETWEEN_SYMBOLS(20, 1293)

/*-----
* ASSIGNMENT a := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),227(105,100),1,1)
------*/
#ifdef XCASELABELS
    case 20:
#endif
      yAssF_SDL_Integer(yVarP->z02C_a, yVarP->z028_frame_to_dl2,
        XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("a := ", &(yVarP->z02C_a),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign("a := ", &(yVarP->z02C_a), (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
      XBETWEEN_SYMBOLS(21, 1311)

/*-----
* ASSIGNMENT frame_to_dl2 := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),230(105,125),1,1)
------*/
#ifdef XCASELABELS
    case 21:
#endif
      yAssF_SDL_Integer(yVarP->z028_frame_to_dl2, yVarP->z026_ack_expected,
        XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("frame_to_dl2 := ", &(yVarP->z028_frame_to_dl2),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign("frame_to_dl2 := ", &(yVarP->z028_frame_to_dl2),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
      XBETWEEN_SYMBOLS(22, 1330)

/*-----
* ASSIGNMENT s... := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),233(105,140),1,1)
------*/
#ifdef XCASELABELS
    case 22:
#endif
      yAssF_z9_Packet(yVarP->z02B_s.Info, yExtr_z022_bufferType(&(yVarP->
        z02E_buffer), &(yVarP->z028_frame_to_dl2)), XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("s... := ", &(yVarP->z02B_s.Info),
        (tSDLTypeInfo *)&ySDL_z9_Packet);
#endif
#ifdef XMSCE
      xMSCEAssign("s... := ", &(yVarP->z02B_s.Info),
        (tSDLTypeInfo *)&ySDL_z9_Packet);
#endif
      XBETWEEN_STMTS(23, 1349)

/*-----
* ASSIGNMENT s... := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),233(105,140),2,1)
------*/
#ifdef XCASELABELS
    case 23:
#endif
      yAssF_SDL_Integer(yVarP->z02B_s.seq, yVarP->z028_frame_to_dl2,
        XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("s... := ", &(yVarP->z02B_s.seq),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign("s... := ", &(yVarP->z02B_s.seq),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
      XBETWEEN_SYMBOLS(24, 1368)

/*-----
* OUTPUT DataToDL2
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),236(105,155),1,1)
------*/
#ifdef XCASELABELS
    case 24:
#endif
      ALLOC_SIGNAL_PAR(DataToDL2, ySigN_z5_DataToDL2, TO_PROCESS(p2,
        yPrsN_z12_p2), yPDef_z5_DataToDL2)
      SIGNAL_ALLOC_ERROR
      yAssF_zA_DataFrame(((yPDef_z5_DataToDL2 *)OUTSIGNAL_DATA_PTR)->Param1,
        &(yVarP->z02B_s), XASS_MR_ASS_NF);
      SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, DataToDL2,
        ySigN_z5_DataToDL2, TO_PROCESS(p2, yPrsN_z12_p2),
        sizeof(yPDef_z5_DataToDL2), "DataToDL2")
      SIGNAL_ALLOC_ERROR_END
      XBETWEEN_SYMBOLS(25, 1386)

/*-----
* RESET T
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),239(105,180),1,1)
------*/
#ifdef XCASELABELS
    case 25:
#endif
      ALLOC_TIMER_SIGNAL_PAR(T, ySigN_z024_T, yPDef_z024_T)
      TIMER_SIGNAL_ALLOC_ERROR
      yAssF_SDL_Integer(((yPDef_z024_T *)TIMER_DATA_PTR)->Param1, yVarP->
        z02D_X, XASS_MR_ASS_NF);
      SDL_RESET_WITH_PARA(yEqT_z024_T, yTim_T, "T")
      TIMER_SIGNAL_ALLOC_ERROR_END
      XBETWEEN_SYMBOLS(26, 1401)

/*-----
* ASSIGNMENT frame_to_dl2 := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),242(105,200),1,1)
------*/
#ifdef XCASELABELS
    case 26:
#endif
      yAssF_SDL_Integer(yVarP->z028_frame_to_dl2, yVarP->z02C_a,
        XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("frame_to_dl2 := ", &(yVarP->z028_frame_to_dl2),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign("frame_to_dl2 := ", &(yVarP->z028_frame_to_dl2),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif

/*-----
* JOIN grst0
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),242(105,200),0)
------*/
      goto L_grst0;
    }

  L_grst0:;
    XBETWEEN_SYMBOLS(30, 1429)

/*-----
* ASSIGNMENT s... := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),269(155,130),1,1)
------*/
#ifdef XCASELABELS
  case 30:
#endif
    yAssF_z9_Packet(yVarP->z02B_s.Info, yExtr_z022_bufferType(&(yVarP->
      z02E_buffer), &(yVarP->z028_frame_to_dl2)), XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("s... := ", &(yVarP->z02B_s.Info),
      (tSDLTypeInfo *)&ySDL_z9_Packet);
#endif
#ifdef XMSCE
    xMSCEAssign("s... := ", &(yVarP->z02B_s.Info),
      (tSDLTypeInfo *)&ySDL_z9_Packet);
#endif
    XBETWEEN_STMTS(31, 1448)

/*-----
* ASSIGNMENT s... := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),269(155,130),2,1)
------*/
#ifdef XCASELABELS
  case 31:
#endif
    yAssF_SDL_Integer(yVarP->z02B_s.seq, yVarP->z028_frame_to_dl2,
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("s... := ", &(yVarP->z02B_s.seq),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("s... := ", &(yVarP->z02B_s.seq),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_SYMBOLS(32, 1467)

/*-----
* OUTPUT DataToDL2
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),275(155,155),1,1)
------*/
#ifdef XCASELABELS
  case 32:
#endif
    ALLOC_SIGNAL_PAR(DataToDL2, ySigN_z5_DataToDL2, TO_PROCESS(p2,
      yPrsN_z12_p2), yPDef_z5_DataToDL2)
    SIGNAL_ALLOC_ERROR
    yAssF_zA_DataFrame(((yPDef_z5_DataToDL2 *)OUTSIGNAL_DATA_PTR)->Param1,
      &(yVarP->z02B_s), XASS_MR_ASS_NF);
    SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, DataToDL2,
      ySigN_z5_DataToDL2, TO_PROCESS(p2, yPrsN_z12_p2),
      sizeof(yPDef_z5_DataToDL2), "DataToDL2")
    SIGNAL_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS(33, 1485)

/*-----
* RESET T
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),278(155,175),1,1)
------*/
#ifdef XCASELABELS
  case 33:
#endif
    ALLOC_TIMER_SIGNAL_PAR(T, ySigN_z024_T, yPDef_z024_T)
    TIMER_SIGNAL_ALLOC_ERROR
    yAssF_SDL_Integer(((yPDef_z024_T *)TIMER_DATA_PTR)->Param1, yVarP->z02D_X,
      XASS_MR_ASS_NF);
    SDL_RESET_WITH_PARA(yEqT_z024_T, yTim_T, "T")
    TIMER_SIGNAL_ALLOC_ERROR_END
    XBETWEEN_SYMBOLS(34, 1500)

/*-----
* DECISION
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),281(155,195),1,1)
------*/
#ifdef XCASELABELS
  case 34:
#endif
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, xGT_SDL_Integer(yVarP->z029_nbuffered,
      SDL_INTEGER_LIT(0)), XASS_MR_ASS_FR);
    xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
    xMSCEDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    if (yDcn_SDL_Boolean) {
#else
    if (xGT_SDL_Integer(yVarP->z029_nbuffered, SDL_INTEGER_LIT(0))) {
#endif
      XBETWEEN_SYMBOLS(36, 1520)

/*-----
* ASSIGNMENT frame_to_dl2 := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),284(155,215),1,1)
------*/
#ifdef XCASELABELS
    case 36:
#endif
      yAssF_SDL_Integer(yVarP->z028_frame_to_dl2, xPlus_SDL_Integer(yVarP->
        z028_frame_to_dl2, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
      xTraceAssign("frame_to_dl2 := ", &(yVarP->z028_frame_to_dl2),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
      xMSCEAssign("frame_to_dl2 := ", &(yVarP->z028_frame_to_dl2),
        (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    } else {
      XBETWEEN_SYMBOLS(35, 1540)

/*-----
* NEXTSTATE Wait
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),287(130,205),1)
------*/
#ifdef XCASELABELS
    case 35:
#endif
      XAT_LAST_SYMBOL
      SDL_NEXTSTATE(Wait, z023_Wait, "Wait")
    }

/*-----
* JOIN grst0
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),269(155,130),1)
------*/
    goto L_grst0;

/*-----
* INPUT T
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),263(155,85),1)
------*/
  case 3:
    XDEBUG_LABEL(Wait_T)
    XAT_FIRST_SYMBOL(3)
    XOS_TRACE_INPUT("T")
    INPUT_TIMER_VAR_PARA(yTim_T)
    yAssF_SDL_Integer(yVarP->z02D_X, ((yPDef_z024_T *)ySVarP)->Param1,
      XASS_AR_ASS_FR);
    XBETWEEN_SYMBOLS(37, 1570)

/*-----
* ASSIGNMENT frame_to_dl2 := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),266(155,110),1,1)
------*/
#ifdef XCASELABELS
  case 37:
#endif
    yAssF_SDL_Integer(yVarP->z028_frame_to_dl2, yVarP->z026_ack_expected,
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("frame_to_dl2 := ", &(yVarP->z028_frame_to_dl2),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("frame_to_dl2 := ", &(yVarP->z028_frame_to_dl2),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif

/*-----
* JOIN grst0
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),269(155,130),1)
------*/
    goto L_grst0;
  }
}

/*****
* STATE Wait
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),137(85,60),1,1)
******/
static XCONST xInputAction yStaH_z023_Wait[] = {xEnablCond, xInput, xInput,
  xDiscard};
static XCONST XINPUTREFTYPE yStaI_z023_Wait[] = {1, 2, 3, 0};
#ifdef XCOVERAGE
static long int yStaC_z023_Wait[3+1];
#endif
XCONST struct xStateIdStruct yStaR_z023_Wait = {xStateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "Wait" XCOMMON_EXTRAS, z023_Wait,
  yStaH_z023_Wait, yStaI_z023_Wait, yEnab_z023_Wait, 0, 0
  xCoverage(yStaC_z023_Wait), (xStateIdNode)0
  xBreakB("#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),137(85,60),1,1)")
  XSTA_EXTRAS};

/*------------------------------------------------------------------------
--  Enabling condition function for state Wait
------------------------------------------------------------------------*/
#ifndef XNOENABCONDFUNC
xInputAction yEnab_z023_Wait (XSIGTYPE SignalId, void * VarP)
{
  yVDef_z02_p1 * yVarP = (yVDef_z02_p1 *) VarP;
  if ( (SignalId == SIGNAL_NAME(FromNW1, &ySigR_z6_FromNW1)) ) {
                /* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),146(20,105),1) */
    if (xLT_SDL_Integer(yVarP->z029_nbuffered, SDL_INTEGER_LIT(4)))
      return xInput;
    return xSave;
  }
  return xSave;
}
#endif

/*****
* TIMER T
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),12,7)
******/
static xSignalNode ySigA_z024_T = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z024_T = {xTimerEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "T" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z024_T), &ySigA_z024_T, yEqT_z024_T xFreS(0) SIGCODE(T)
  xBreakB("#SDTREF(SDL,D:\\GoBackN\\project\\project\\p1.spr(1),119(135,10),12,7)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z024_T = {xSignalParEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySigR_z024_T xIdNames(" ") XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yPDef_z024_T, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Equal function for timer T
------------------------------------------------------------------------*/
#ifndef XNOEQTIMERFUNC
extern xbool yEqT_z024_T (void * VarP1, void * VarP2)
{
  if ( yNEqF_SDL_Integer(((yPDef_z024_T *)VarP1)->Param1,
    ((yPDef_z024_T *)VarP2)->Param1) ) return (xbool)0;
  return (xbool)1;
}
#endif

/*****
* DCL next_frame_to_send
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),2,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z025_next_frame_to_send = {xVariableEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "next_frame_to_send"
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yVDef_z02_p1, z025_next_frame_to_send), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL ack_expected
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),3,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z026_ack_expected = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "ack_expected" XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yVDef_z02_p1, z026_ack_expected), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL next_frame_expected
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),4,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z027_next_frame_expected = {xVariableEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "next_frame_expected"
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yVDef_z02_p1, z027_next_frame_expected), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL frame_to_dl2
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),5,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z028_frame_to_dl2 = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "frame_to_dl2" XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yVDef_z02_p1, z028_frame_to_dl2), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL nbuffered
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),6,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z029_nbuffered = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "nbuffered" XCOMMON_EXTRAS,
  &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yVDef_z02_p1, z029_nbuffered), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL r
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),7,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02A_r = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "r" XCOMMON_EXTRAS, &ySrtR_zB_AckFrame,
  (tSDLTypeInfo *)&ySDL_zB_AckFrame, xOffsetOf(yVDef_z02_p1, z02A_r),
  (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL s
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),8,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02B_s = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "s" XCOMMON_EXTRAS, &ySrtR_zA_DataFrame,
  (tSDLTypeInfo *)&ySDL_zA_DataFrame, xOffsetOf(yVDef_z02_p1, z02B_s),
  (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL a
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),9,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02C_a = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "a" XCOMMON_EXTRAS, &xSrtR_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_SDL_Integer, xOffsetOf(yVDef_z02_p1, z02C_a),
  (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL X
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),10,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02D_X = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "X" XCOMMON_EXTRAS, &xSrtR_SDL_Integer,
  (tSDLTypeInfo *)&ySDL_SDL_Integer, xOffsetOf(yVDef_z02_p1, z02D_X),
  (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL buffer
* <<SYSTEM GoBackN/BLOCK DataLink1/PROCESS p1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1.spr(1),119(135,10),11,5)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z02E_buffer = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z02_p1, "buffer" XCOMMON_EXTRAS,
  &ySrtR_z022_bufferType, (tSDLTypeInfo *)&ySDL_z022_bufferType,
  xOffsetOf(yVDef_z02_p1, z02E_buffer), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* SIGNALROUTE N11
* <<SYSTEM GoBackN/BLOCK DataLink1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1(1),119(47,72),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z03_N11[] = {SIGNAL_NAME(FromNW1,
  &ySigR_z6_FromNW1), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z03_N11[] = {(XSIGTYPE)0};
XCONST xIdNode yChaO_z03_N11[] = {(xIdNode)&yPrsR_z02_p1, (xIdNode)0};
XCONST xIdNode yChaOR_z03_N11[] = {(xIdNode)&yChaRR_z2_N1, (xIdNode)0};
XCONST struct xChannelIdStruct yChaR_z03_N11 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_DataLink1, "N11" XCOMMON_EXTRAS,
  yChaS_z03_N11, yChaO_z03_N11, &yChaRR_z03_N11 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z03_N11 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_DataLink1, "N11" XCOMMON_EXTRAS,
  yChaSR_z03_N11, yChaOR_z03_N11, &yChaR_z03_N11 XCHA_EXTRAS};
#endif

/*****
* SIGNALROUTE R1
* <<SYSTEM GoBackN/BLOCK DataLink1>>
* #SDTREF(SDL,D:\GoBackN\project\project\p1(1),140(142,72),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z04_R1[] = {SIGNAL_NAME(DataToDL2,
  &ySigR_z5_DataToDL2), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z04_R1[] = {SIGNAL_NAME(AckToDL1,
  &ySigR_z8_AckToDL1), (XSIGTYPE)0};
XCONST xIdNode yChaO_z04_R1[] = {(xIdNode)&yChaRR_z3_R, (xIdNode)0};
XCONST xIdNode yChaOR_z04_R1[] = {(xIdNode)&yPrsR_z02_p1, (xIdNode)0};
XCONST struct xChannelIdStruct yChaR_z04_R1 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_DataLink1, "R1" XCOMMON_EXTRAS, yChaS_z04_R1,
  yChaO_z04_R1, &yChaRR_z04_R1 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z04_R1 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z0_DataLink1, "R1" XCOMMON_EXTRAS, yChaSR_z04_R1,
  yChaOR_z04_R1, &yChaR_z04_R1 XCHA_EXTRAS};
#endif

/*****
* BLOCK DataLink2
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.sbk,4,1)
******/
XCONST struct xBlockIdStruct yBloR_z1_DataLink2 = {xBlockEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "DataLink2" XCOMMON_EXTRAS,
  (xBlockIdNode)0, (xIdNode *)0, (xPrdIdNode *)0, (xViewListRec *)0,
  (xViewIndexRec *)0, 1 xTrace(-1) xGRTrace(-1) xMSCETrace(-1) xMSCETrace(0)
  XBLO_EXTRAS};
#ifndef XOPTCHAN
XCONST xIdNode yChaOR_z3_R[] = {(xIdNode)&yChaRR_z13_R2, (xIdNode)0};
XCONST xIdNode yChaOR_z4_N2[] = {(xIdNode)&yChaRR_z14_N21, (xIdNode)0};
#endif

/*****
* PROCESS p2
* <<SYSTEM GoBackN/BLOCK DataLink2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr,4,1)
******/
#ifdef XCOVERAGE
long int yPrsC_z12_p2[ySym_z12_p2+1];
#endif
XCONST XSIGTYPE yPrsS_z12_p2[] = {SIGNAL_NAME(DataToDL2, &ySigR_z5_DataToDL2),
  (XSIGTYPE)0};
XCONST xStateIdNode yPrsT_z12_p2[] = {&xStartStateIdRec, &yStaR_z121_Wait};
static XPRSNODE yPrsA_z12_p2 = (XPRSNODE)0;
static XPRSNODE yPrsB_z12_p2 = (XPRSNODE)0;
XCONST struct xPrsIdStruct yPrsR_z12_p2 = {xProcessEC , (xIdNode)0, (xIdNode)0,
  (xIdNode)&yBloR_z1_DataLink2, "p2" XCOMMON_EXTRAS, yPrsT_z12_p2,
  yPrsS_z12_p2 xService(0) xOptChan(yPrsO_z12_p2), -1 xNrInst(1) xNrInst(1),
  &yPrsB_z12_p2, (xptrint)sizeof(yVDef_z12_p2)
  xPrsPrioPar(xDefaultPrioProcess), &yPrsA_z12_p2 xTrace(-1) xGRTrace(-1)
  xBreakB(yRef_z12_p2) xBreakB(ySym_z12_p2) xBreakB(1) xMSCETrace(-1)
  xCoverage(yPrsC_z12_p2) xCoverage(0) xCoverage(0), yPAD_z12_p2, yFree_z12_p2,
  (xPrsIdNode)0, (xPrdIdNode *)0, (xBlockIdNode)0
  xBreakB("#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr,4,1)")
  xThreadName(0) xThreadName(0) XPRS_EXTRAS(z12_p2)};
static xSignalNode ySigA_z12_p2 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z12_p2 = {xStartUpSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z1_DataLink2 xIdNames("-") XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z12_p2), &ySigA_z12_p2, 0 xFreS(0)
  SIGCODE(STARTUPSIGNAL)
  xBreakB("#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr,4,1)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
XPROCESSDEF_C(p2,"p2",z12_p2,yPAD_z12_p2,yVDef_z12_p2)
#ifndef XOPTCHAN
XCONST xIdNode yPrsO_z12_p2[] = {(xIdNode)&yChaR_z13_R2,
  (xIdNode)&yChaR_z14_N21, (xIdNode)0};
#endif
void yFree_z12_p2(void *yVarP)
{
  yFree_zA_DataFrame((void **)&((yVDef_z12_p2 *)yVarP)->z123_r);
}

/*+++++
* GR ref function for process p2
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr,4,1)
++++++*/
#ifdef XBREAKBEFORE
extern char * yRef_z12_p2 (int SymbolNo, xSymbolType *SymbolType)
{
  switch (SymbolNo) {
    case 0: *SymbolType = xsStart;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),119(85,5),1)";
    case 1: *SymbolType = xsInput;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),131(85,50),1)";
    case 2: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),122(85,20),1,1)";
    case 3: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),128(85,35),1)";
    case 4: *SymbolType = xsDecision;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),170(85,65),1,1)";
    case 5: *SymbolType = xsDecision;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),221(35,75),1,1)";
    case 6: *SymbolType = xsOutput;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),233(35,95),1,1)";
    case 7: *SymbolType = xsDecision;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),134(85,85),1,1)";
    case 8: *SymbolType = xsOutput;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),158(85,105),1,1)";
    case 9: *SymbolType = xsOutput;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),188(85,120),1,1)";
    case 10: *SymbolType = xsAssignmentStatement;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),194(85,135),1,1)";
    case 11: *SymbolType = xsNextstate;
      return "#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),197(85,155),1)";
    default : *SymbolType = xsNoSuchSymbolType; return "";
  }
}
#endif

/*+++++
* Function for process p2
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr,4,1)
++++++*/
YPAD_FUNCTION(yPAD_z12_p2)
{
  YPAD_YSVARP
  YPAD_YVARP(yVDef_z12_p2)
  YPAD_TEMP_VARS
#ifdef XTRACE
  SDL_Boolean yDcn_SDL_Boolean;
#endif
  YPRSNAME_VAR("p2")

  BEGIN_PAD(yVDef_z12_p2)

  LOOP_LABEL
  switch (yVarP->RestartAddress) {

/*-----
* START
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),119(85,5),1)
------*/
  case 0:
    BEGIN_START_TRANSITION(yPDef_z12_p2)
    XAT_FIRST_SYMBOL(0)
    XBETWEEN_SYMBOLS(2, 1940)

/*-----
* ASSIGNMENT frame_expected := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),122(85,20),1,1)
------*/
#ifdef XCASELABELS
  case 2:
#endif
    yAssF_SDL_Integer(yVarP->z122_frame_expected, SDL_INTEGER_LIT(0),
      XASS_MR_ASS_FR);
#ifdef XTRACE
    xTraceAssign("frame_expected := ", &(yVarP->z122_frame_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
    xMSCEAssign("frame_expected := ", &(yVarP->z122_frame_expected),
      (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
    XBETWEEN_SYMBOLS(3, 1959)

/*-----
* NEXTSTATE Wait
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),128(85,35),1)
------*/
#ifdef XCASELABELS
  case 3:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(Wait, z121_Wait, "Wait")

/*-----
* INPUT DataToDL2
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),131(85,50),1)
------*/
  case 1:
    XDEBUG_LABEL(Wait_DataToDL2)
    XAT_FIRST_SYMBOL(1)
    XOS_TRACE_INPUT("DataToDL2")
#ifdef XVALIDATOR_LIB
    yAssF_zA_DataFrame(yVarP->z123_r, &(((yPDef_z5_DataToDL2 *)ySVarP)->
      Param1), XASS_MR_ASS_FR);
#else
    yAssF_zA_DataFrame(yVarP->z123_r, &(((yPDef_z5_DataToDL2 *)ySVarP)->
      Param1), XASS_AR_ASS_FR);
#endif
    XBETWEEN_SYMBOLS(4, 1986)

/*-----
* DECISION
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),170(85,65),1,1)
------*/
#ifdef XCASELABELS
  case 4:
#endif
#ifdef XTRACE
    yAssF_SDL_Boolean(yDcn_SDL_Boolean, yEqF_SDL_Integer(yVarP->z123_r.seq,
      yVarP->z122_frame_expected), XASS_MR_ASS_FR);
    xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
    xMSCEDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
    if (yDcn_SDL_Boolean) {
#else
    if (yEqF_SDL_Integer(yVarP->z123_r.seq, yVarP->z122_frame_expected)) {
#endif
      XBETWEEN_SYMBOLS(7, 2006)

/*-----
* DECISION
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),134(85,85),1,1)
------*/
#ifdef XCASELABELS
    case 7:
#endif
#ifdef XTRACE
      yAssF_SDL_Boolean(yDcn_SDL_Boolean, yEqF_SDL_Integer(yVarP->z123_r.Flag,
        SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
      xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
      xMSCEDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
      if (yDcn_SDL_Boolean) {
#else
      if (yEqF_SDL_Integer(yVarP->z123_r.Flag, SDL_INTEGER_LIT(1))) {
#endif
      } else {
        XBETWEEN_SYMBOLS(8, 2027)

/*-----
* OUTPUT AckToDL1
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),158(85,105),1,1)
------*/
#ifdef XCASELABELS
      case 8:
#endif
        ALLOC_SIGNAL_PAR(AckToDL1, ySigN_z8_AckToDL1, TO_PROCESS(p1,
          yPrsN_z02_p1), yPDef_z8_AckToDL1)
        SIGNAL_ALLOC_ERROR
        yAssF_zB_AckFrame(((yPDef_z8_AckToDL1 *)OUTSIGNAL_DATA_PTR)->Param1,
          &(yVarP->z124_s), XASS_MR_ASS_NF);
        SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, AckToDL1,
          ySigN_z8_AckToDL1, TO_PROCESS(p1, yPrsN_z02_p1),
          sizeof(yPDef_z8_AckToDL1), "AckToDL1")
        SIGNAL_ALLOC_ERROR_END
        XBETWEEN_SYMBOLS(9, 2045)

/*-----
* OUTPUT ToNW2
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),188(85,120),1,1)
------*/
#ifdef XCASELABELS
      case 9:
#endif
        ALLOC_SIGNAL_PAR(ToNW2, ySigN_z7_ToNW2, TO_PROCESS(Env, &yEnvR_env),
          yPDef_z7_ToNW2)
        SIGNAL_ALLOC_ERROR
        yAssF_z9_Packet(((yPDef_z7_ToNW2 *)OUTSIGNAL_DATA_PTR)->Param1,
          &(yVarP->z123_r.Info), XASS_MR_ASS_NF);
        SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, ToNW2,
          ySigN_z7_ToNW2, TO_PROCESS(Env, &yEnvR_env), sizeof(yPDef_z7_ToNW2),
          "ToNW2")
        SIGNAL_ALLOC_ERROR_END
        XBETWEEN_SYMBOLS(10, 2063)

/*-----
* ASSIGNMENT frame_expected := ...
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),194(85,135),1,1)
------*/
#ifdef XCASELABELS
      case 10:
#endif
        yAssF_SDL_Integer(yVarP->z122_frame_expected, xPlus_SDL_Integer(yVarP->
          z122_frame_expected, SDL_INTEGER_LIT(1)), XASS_MR_ASS_FR);
#ifdef XTRACE
        xTraceAssign("frame_expected := ", &(yVarP->z122_frame_expected),
          (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
#ifdef XMSCE
        xMSCEAssign("frame_expected := ", &(yVarP->z122_frame_expected),
          (tSDLTypeInfo *)&ySDL_SDL_Integer);
#endif
      }
    } else {
      XBETWEEN_SYMBOLS(5, 2084)

/*-----
* DECISION
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),221(35,75),1,1)
------*/
#ifdef XCASELABELS
    case 5:
#endif
#ifdef XTRACE
      yAssF_SDL_Boolean(yDcn_SDL_Boolean, xLT_SDL_Integer(yVarP->z123_r.seq,
        yVarP->z122_frame_expected), XASS_MR_ASS_FR);
      xTraceDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#ifdef XMSCE
      xMSCEDecision(&(yDcn_SDL_Boolean), (tSDLTypeInfo *)&ySDL_SDL_Boolean);
#endif
      if (yDcn_SDL_Boolean) {
#else
      if (xLT_SDL_Integer(yVarP->z123_r.seq, yVarP->z122_frame_expected)) {
#endif
        XBETWEEN_SYMBOLS(6, 2104)

/*-----
* OUTPUT AckToDL1
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),233(35,95),1,1)
------*/
#ifdef XCASELABELS
      case 6:
#endif
        ALLOC_SIGNAL_PAR(AckToDL1, ySigN_z8_AckToDL1, TO_PROCESS(p1,
          yPrsN_z02_p1), yPDef_z8_AckToDL1)
        SIGNAL_ALLOC_ERROR
        yAssF_zB_AckFrame(((yPDef_z8_AckToDL1 *)OUTSIGNAL_DATA_PTR)->Param1,
          &(yVarP->z124_s), XASS_MR_ASS_NF);
        SDL_2OUTPUT_COMPUTED_TO(xDefaultPrioSignal, (xIdNode *)0, AckToDL1,
          ySigN_z8_AckToDL1, TO_PROCESS(p1, yPrsN_z02_p1),
          sizeof(yPDef_z8_AckToDL1), "AckToDL1")
        SIGNAL_ALLOC_ERROR_END
      } else {
      }
    }
    XBETWEEN_SYMBOLS(11, 2125)

/*-----
* NEXTSTATE Wait
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),197(85,155),1)
------*/
#ifdef XCASELABELS
  case 11:
#endif
    XAT_LAST_SYMBOL
    SDL_NEXTSTATE(Wait, z121_Wait, "Wait")
  }
}

/*****
* STATE Wait
* <<SYSTEM GoBackN/BLOCK DataLink2/PROCESS p2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),128(85,35),1,1)
******/
static XCONST xInputAction yStaH_z121_Wait[] = {xInput, xDiscard};
static XCONST XINPUTREFTYPE yStaI_z121_Wait[] = {1, 0};
#ifdef XCOVERAGE
static long int yStaC_z121_Wait[1+1];
#endif
XCONST struct xStateIdStruct yStaR_z121_Wait = {xStateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z12_p2, "Wait" XCOMMON_EXTRAS, z121_Wait,
  yStaH_z121_Wait, yStaI_z121_Wait, 0, 0, 0 xCoverage(yStaC_z121_Wait),
  (xStateIdNode)0
  xBreakB("#SDTREF(SDL,D:\\GoBackN\\project\\project\\p2.spr(1),128(85,35),1,1)")
  XSTA_EXTRAS};

/*****
* DCL frame_expected
* <<SYSTEM GoBackN/BLOCK DataLink2/PROCESS p2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),218(35,15),2,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z122_frame_expected = {xVariableEC ,
  (xIdNode)0, (xIdNode)0, (xIdNode)&yPrsR_z12_p2, "frame_expected"
  XCOMMON_EXTRAS, &xSrtR_SDL_Integer, (tSDLTypeInfo *)&ySDL_SDL_Integer,
  xOffsetOf(yVDef_z12_p2, z122_frame_expected), (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL r
* <<SYSTEM GoBackN/BLOCK DataLink2/PROCESS p2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),218(35,15),3,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z123_r = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z12_p2, "r" XCOMMON_EXTRAS, &ySrtR_zA_DataFrame,
  (tSDLTypeInfo *)&ySDL_zA_DataFrame, xOffsetOf(yVDef_z12_p2, z123_r),
  (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* DCL s
* <<SYSTEM GoBackN/BLOCK DataLink2/PROCESS p2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.spr(1),218(35,15),4,1)
******/
#ifndef XOPTDCL
XCONST struct xVarIdStruct yVarR_z124_s = {xVariableEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yPrsR_z12_p2, "s" XCOMMON_EXTRAS, &ySrtR_zB_AckFrame,
  (tSDLTypeInfo *)&ySDL_zB_AckFrame, xOffsetOf(yVDef_z12_p2, z124_s),
  (xptrint)0, 0 XVAR_EXTRAS};
#endif

/*****
* SIGNALROUTE R2
* <<SYSTEM GoBackN/BLOCK DataLink2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.sbk(1),167(42,82),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z13_R2[] = {SIGNAL_NAME(AckToDL1,
  &ySigR_z8_AckToDL1), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z13_R2[] = {SIGNAL_NAME(DataToDL2,
  &ySigR_z5_DataToDL2), (XSIGTYPE)0};
XCONST xIdNode yChaO_z13_R2[] = {(xIdNode)&yChaR_z3_R, (xIdNode)0};
XCONST xIdNode yChaOR_z13_R2[] = {(xIdNode)&yPrsR_z12_p2, (xIdNode)0};
XCONST struct xChannelIdStruct yChaR_z13_R2 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z1_DataLink2, "R2" XCOMMON_EXTRAS, yChaS_z13_R2,
  yChaO_z13_R2, &yChaRR_z13_R2 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z13_R2 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z1_DataLink2, "R2" XCOMMON_EXTRAS, yChaSR_z13_R2,
  yChaOR_z13_R2, &yChaR_z13_R2 XCHA_EXTRAS};
#endif

/*****
* SIGNALROUTE N21
* <<SYSTEM GoBackN/BLOCK DataLink2>>
* #SDTREF(SDL,D:\GoBackN\project\project\p2.sbk(1),140(139,82),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z14_N21[] = {SIGNAL_NAME(ToNW2, &ySigR_z7_ToNW2),
  (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z14_N21[] = {(XSIGTYPE)0};
XCONST xIdNode yChaO_z14_N21[] = {(xIdNode)&yChaR_z4_N2, (xIdNode)0};
XCONST xIdNode yChaOR_z14_N21[] = {(xIdNode)&yPrsR_z12_p2, (xIdNode)0};
XCONST struct xChannelIdStruct yChaR_z14_N21 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z1_DataLink2, "N21" XCOMMON_EXTRAS,
  yChaS_z14_N21, yChaO_z14_N21, &yChaRR_z14_N21 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z14_N21 = {xSignalrouteEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&yBloR_z1_DataLink2, "N21" XCOMMON_EXTRAS,
  yChaSR_z14_N21, yChaOR_z14_N21, &yChaR_z14_N21 XCHA_EXTRAS};
#endif

/*****
* CHANNEL N1
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),146(30,90),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z2_N1[] = {SIGNAL_NAME(FromNW1,
  &ySigR_z6_FromNW1), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z2_N1[] = {(XSIGTYPE)0};
#ifndef XMULTIPLESYSTEMS
XCONST xIdNode yChaOR_z2_N1[] = {(xIdNode)&yEnvR_env, (xIdNode)0};
#else
XCONST xIdNode yChaOR_z2_N1[] = {(xIdNode)&yGateOut_GoBackN_N1, (xIdNode)0};
#endif
XCONST struct xChannelIdStruct yChaR_z2_N1 = {xChannelEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "N1" XCOMMON_EXTRAS, yChaS_z2_N1,
  yChaO_z2_N1, &yChaRR_z2_N1 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z2_N1 = {xChannelEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "N1" XCOMMON_EXTRAS, yChaSR_z2_N1,
  yChaOR_z2_N1, &yChaR_z2_N1 XCHA_EXTRAS};
#ifdef XMULTIPLESYSTEMS
XCONST xIdNode yConnIn_GoBackN_N1[] = {(xIdNode)&yChaR_z2_N1, (xIdNode)0};
XCONST struct xChannelIdStruct yGateIn_GoBackN_N1= {xGateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN xIdNames("GoBackN_N1") XCOMMON_EXTRAS,
  yChaS_z2_N1, yConnIn_GoBackN_N1, &yGateOut_GoBackN_N1 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yGateOut_GoBackN_N1= {xGateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN xIdNames("GoBackN_N1") XCOMMON_EXTRAS,
  yChaSR_z2_N1, yConnOut_GoBackN_N1, &yGateIn_GoBackN_N1 XCHA_EXTRAS};
#endif
#endif

/*****
* CHANNEL R
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),134(100,90),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z3_R[] = {SIGNAL_NAME(AckToDL1,
  &ySigR_z8_AckToDL1), (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z3_R[] = {SIGNAL_NAME(DataToDL2,
  &ySigR_z5_DataToDL2), (XSIGTYPE)0};
XCONST struct xChannelIdStruct yChaR_z3_R = {xChannelEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "R" XCOMMON_EXTRAS, yChaS_z3_R,
  yChaO_z3_R, &yChaRR_z3_R XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z3_R = {xChannelEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "R" XCOMMON_EXTRAS, yChaSR_z3_R,
  yChaOR_z3_R, &yChaR_z3_R XCHA_EXTRAS};
#endif

/*****
* CHANNEL N2
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),137(165,90),1,1)
******/
#ifndef XOPTCHAN
static XCONST XSIGTYPE yChaS_z4_N2[] = {SIGNAL_NAME(ToNW2, &ySigR_z7_ToNW2),
  (XSIGTYPE)0};
static XCONST XSIGTYPE yChaSR_z4_N2[] = {(XSIGTYPE)0};
#ifndef XMULTIPLESYSTEMS
XCONST xIdNode yChaO_z4_N2[] = {(xIdNode)&yEnvR_env, (xIdNode)0};
#else
XCONST xIdNode yChaO_z4_N2[] = {(xIdNode)&yGateOut_GoBackN_N2, (xIdNode)0};
#endif
XCONST struct xChannelIdStruct yChaR_z4_N2 = {xChannelEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "N2" XCOMMON_EXTRAS, yChaS_z4_N2,
  yChaO_z4_N2, &yChaRR_z4_N2 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yChaRR_z4_N2 = {xChannelEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "N2" XCOMMON_EXTRAS, yChaSR_z4_N2,
  yChaOR_z4_N2, &yChaR_z4_N2 XCHA_EXTRAS};
#ifdef XMULTIPLESYSTEMS
XCONST xIdNode yConnIn_GoBackN_N2[] = {(xIdNode)&yChaRR_z4_N2, (xIdNode)0};
XCONST struct xChannelIdStruct yGateIn_GoBackN_N2= {xGateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN xIdNames("GoBackN_N2") XCOMMON_EXTRAS,
  yChaSR_z4_N2, yConnIn_GoBackN_N2, &yGateOut_GoBackN_N2 XCHA_EXTRAS};
XCONST struct xChannelIdStruct yGateOut_GoBackN_N2= {xGateEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN xIdNames("GoBackN_N2") XCOMMON_EXTRAS,
  yChaS_z4_N2, yConnOut_GoBackN_N2, &yGateIn_GoBackN_N2 XCHA_EXTRAS};
#endif
#endif

/*****
* SIGNAL DataToDL2
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),158(125,30),2,1)
******/
static xSignalNode ySigA_z5_DataToDL2 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z5_DataToDL2 = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "DataToDL2" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z5_DataToDL2), &ySigA_z5_DataToDL2, 0
  xFreS(yFree_z5_DataToDL2) SIGCODE(DataToDL2)
  xBreakB("#SDTREF(SDL,D:\\GoBackN\\project\\project\\goback.ssy(1),158(125,30),2,1)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z5_DataToDL2 = {xSignalParEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySigR_z5_DataToDL2 xIdNames(" ") XCOMMON_EXTRAS,
  &ySrtR_zA_DataFrame, (tSDLTypeInfo *)&ySDL_zA_DataFrame,
  xOffsetOf(yPDef_z5_DataToDL2, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Free function for signal DataToDL2
------------------------------------------------------------------------*/

#ifdef XFREESIGNALFUNCS
void yFree_z5_DataToDL2 (void *SVarP)
{
  yFree_zA_DataFrame((void **)&((yPDef_z5_DataToDL2 *)SVarP)->Param1);
}
#endif

/*****
* SIGNAL FromNW1
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),158(125,30),3,1)
******/
static xSignalNode ySigA_z6_FromNW1 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z6_FromNW1 = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "FromNW1" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z6_FromNW1), &ySigA_z6_FromNW1, 0
  xFreS(yFree_z6_FromNW1) SIGCODE(FromNW1)
  xBreakB("#SDTREF(SDL,D:\\GoBackN\\project\\project\\goback.ssy(1),158(125,30),3,1)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z6_FromNW1 = {xSignalParEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySigR_z6_FromNW1 xIdNames(" ") XCOMMON_EXTRAS,
  &ySrtR_z9_Packet, (tSDLTypeInfo *)&ySDL_z9_Packet,
  xOffsetOf(yPDef_z6_FromNW1, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Free function for signal FromNW1
------------------------------------------------------------------------*/

#ifdef XFREESIGNALFUNCS
void yFree_z6_FromNW1 (void *SVarP)
{
  yFree_z9_Packet((void **)&((yPDef_z6_FromNW1 *)SVarP)->Param1);
}
#endif

/*****
* SIGNAL ToNW2
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),158(125,30),4,1)
******/
static xSignalNode ySigA_z7_ToNW2 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z7_ToNW2 = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "ToNW2" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z7_ToNW2), &ySigA_z7_ToNW2, 0 xFreS(yFree_z7_ToNW2)
  SIGCODE(ToNW2)
  xBreakB("#SDTREF(SDL,D:\\GoBackN\\project\\project\\goback.ssy(1),158(125,30),4,1)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z7_ToNW2 = {xSignalParEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySigR_z7_ToNW2 xIdNames(" ") XCOMMON_EXTRAS,
  &ySrtR_z9_Packet, (tSDLTypeInfo *)&ySDL_z9_Packet,
  xOffsetOf(yPDef_z7_ToNW2, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*------------------------------------------------------------------------
--  Free function for signal ToNW2
------------------------------------------------------------------------*/

#ifdef XFREESIGNALFUNCS
void yFree_z7_ToNW2 (void *SVarP)
{
  yFree_z9_Packet((void **)&((yPDef_z7_ToNW2 *)SVarP)->Param1);
}
#endif

/*****
* SIGNAL AckToDL1
* <<SYSTEM GoBackN>>
* #SDTREF(SDL,D:\GoBackN\project\project\goback.ssy(1),158(125,30),5,1)
******/
static xSignalNode ySigA_z8_AckToDL1 = (xSignalNode)0;
XCONST struct xSignalIdStruct ySigR_z8_AckToDL1 = {xSignalEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySysR_z_GoBackN, "AckToDL1" XCOMMON_EXTRAS,
  (xptrint)sizeof(yPDef_z8_AckToDL1), &ySigA_z8_AckToDL1, 0 xFreS(0)
  SIGCODE(AckToDL1)
  xBreakB("#SDTREF(SDL,D:\\GoBackN\\project\\project\\goback.ssy(1),158(125,30),5,1)")
  xSigPrioPar(xDefaultPrioSignal) XSIG_EXTRAS};
#ifndef XOPTSIGPARA
XCONST struct xVarIdStruct ySPaR1_z8_AckToDL1 = {xSignalParEC , (xIdNode)0,
  (xIdNode)0, (xIdNode)&ySigR_z8_AckToDL1 xIdNames(" ") XCOMMON_EXTRAS,
  &ySrtR_zB_AckFrame, (tSDLTypeInfo *)&ySDL_zB_AckFrame,
  xOffsetOf(yPDef_z8_AckToDL1, Param1), (xptrint)0, (xbool)0 XSPA_EXTRAS};
#endif

/*************************************************************************
**                       SECTION Initialization                         **
*************************************************************************/
#ifndef XMULTIPLESYSTEMS
extern void yInit (void)
{
#else
extern void yInit_GoBackN (void)
{
#endif
  int  Temp;
  YINIT_TEMP_VARS
  BEGIN_YINIT

#ifdef XMONITOR
  xTranslatorVersion =
    "Program generated by Cbasic 4.3.0 ";
#endif
  xInsertIdNode((xIdNode)&ySysR_z_GoBackN);
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z9_Packet);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_z97_Data);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_zA_DataFrame);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_zAB_Info);
  xInsertIdNode((xIdNode)&yVarR_zAC_seq);
  xInsertIdNode((xIdNode)&yVarR_zAD_Flag);
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_zB_AckFrame);
#endif
#ifndef XOPTSTRUCT
  xInsertIdNode((xIdNode)&yVarR_zB9_Ack);
  xInsertIdNode((xIdNode)&yVarR_zBA_seq);
#endif
  xInsertIdNode((xIdNode)&yBloR_z0_DataLink1);
  xInsertIdNode((xIdNode)&yPrsR_z02_p1);
  xInsertIdNode((xIdNode)&ySigR_z02_p1);
  INIT_PROCESS_TYPE(p1,z02_p1,yPrsN_z02_p1,"z02_p1",-1,1,yVDef_z02_p1,
    xDefaultPrioProcess,yPAD_z02_p1)
#ifdef SDL_STATIC_CREATE
  SDL_STATIC_CREATE(p1,z02_p1,yPrsN_z02_p1,"p1",ySigN_z02_p1,yPDef_z02_p1,
    yVDef_z02_p1,xDefaultPrioProcess,yPAD_z02_p1,1)
#endif
#ifndef XOPTSORT
  xInsertIdNode((xIdNode)&ySrtR_z022_bufferType);
#endif
  xInsertIdNode((xIdNode)&yStaR_z023_Wait);
  xInsertIdNode((xIdNode)&ySigR_z024_T);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z024_T);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z025_next_frame_to_send);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z026_ack_expected);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z027_next_frame_expected);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z028_frame_to_dl2);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z029_nbuffered);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02A_r);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02B_s);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02C_a);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02D_X);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z02E_buffer);
#endif
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z03_N11);
  xInsertIdNode((xIdNode)&yChaRR_z03_N11);
#endif
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z04_R1);
  xInsertIdNode((xIdNode)&yChaRR_z04_R1);
#endif
  xInsertIdNode((xIdNode)&yBloR_z1_DataLink2);
  xInsertIdNode((xIdNode)&yPrsR_z12_p2);
  xInsertIdNode((xIdNode)&ySigR_z12_p2);
  INIT_PROCESS_TYPE(p2,z12_p2,yPrsN_z12_p2,"z12_p2",-1,1,yVDef_z12_p2,
    xDefaultPrioProcess,yPAD_z12_p2)
#ifdef SDL_STATIC_CREATE
  SDL_STATIC_CREATE(p2,z12_p2,yPrsN_z12_p2,"p2",ySigN_z12_p2,yPDef_z12_p2,
    yVDef_z12_p2,xDefaultPrioProcess,yPAD_z12_p2,1)
#endif
  xInsertIdNode((xIdNode)&yStaR_z121_Wait);
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z122_frame_expected);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z123_r);
#endif
#ifndef XOPTDCL
  xInsertIdNode((xIdNode)&yVarR_z124_s);
#endif
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z13_R2);
  xInsertIdNode((xIdNode)&yChaRR_z13_R2);
#endif
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z14_N21);
  xInsertIdNode((xIdNode)&yChaRR_z14_N21);
#endif
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z2_N1);
  xInsertIdNode((xIdNode)&yChaRR_z2_N1);
#endif
#ifdef XMULTIPLESYSTEMS
  xInsertIdNode((xIdNode)&yGateIn_GoBackN_N1);
  xInsertIdNode((xIdNode)&yGateOut_GoBackN_N1);
#endif
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z3_R);
  xInsertIdNode((xIdNode)&yChaRR_z3_R);
#endif
#ifndef XOPTCHAN
  xInsertIdNode((xIdNode)&yChaR_z4_N2);
  xInsertIdNode((xIdNode)&yChaRR_z4_N2);
#endif
#ifdef XMULTIPLESYSTEMS
  xInsertIdNode((xIdNode)&yGateIn_GoBackN_N2);
  xInsertIdNode((xIdNode)&yGateOut_GoBackN_N2);
#endif
  xInsertIdNode((xIdNode)&ySigR_z5_DataToDL2);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z5_DataToDL2);
#endif
#if defined(XFREESIGNALFUNCS) && defined(XNOSIGNALIDNODE)
  RegSignalFreeFunc(DataToDL2, yFree_z5_DataToDL2);
#endif
  xInsertIdNode((xIdNode)&ySigR_z6_FromNW1);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z6_FromNW1);
#endif
#if defined(XFREESIGNALFUNCS) && defined(XNOSIGNALIDNODE)
  RegSignalFreeFunc(FromNW1, yFree_z6_FromNW1);
#endif
  xInsertIdNode((xIdNode)&ySigR_z7_ToNW2);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z7_ToNW2);
#endif
#if defined(XFREESIGNALFUNCS) && defined(XNOSIGNALIDNODE)
  RegSignalFreeFunc(ToNW2, yFree_z7_ToNW2);
#endif
  xInsertIdNode((xIdNode)&ySigR_z8_AckToDL1);
#ifndef XOPTSIGPARA
  xInsertIdNode((xIdNode)&ySPaR1_z8_AckToDL1);
#endif
}
