
package webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StringServiceService", targetNamespace = "http://webservice/", wsdlLocation = "http://localhost:9090/stringService?wsdl")
public class StringServiceService
    extends Service
{

    private final static URL STRINGSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException STRINGSERVICESERVICE_EXCEPTION;
    private final static QName STRINGSERVICESERVICE_QNAME = new QName("http://webservice/", "StringServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/stringService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STRINGSERVICESERVICE_WSDL_LOCATION = url;
        STRINGSERVICESERVICE_EXCEPTION = e;
    }

    public StringServiceService() {
        super(__getWsdlLocation(), STRINGSERVICESERVICE_QNAME);
    }

    public StringServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STRINGSERVICESERVICE_QNAME, features);
    }

    public StringServiceService(URL wsdlLocation) {
        super(wsdlLocation, STRINGSERVICESERVICE_QNAME);
    }

    public StringServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STRINGSERVICESERVICE_QNAME, features);
    }

    public StringServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StringServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StringService
     */
    @WebEndpoint(name = "StringServicePort")
    public StringService getStringServicePort() {
        return super.getPort(new QName("http://webservice/", "StringServicePort"), StringService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StringService
     */
    @WebEndpoint(name = "StringServicePort")
    public StringService getStringServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice/", "StringServicePort"), StringService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STRINGSERVICESERVICE_EXCEPTION!= null) {
            throw STRINGSERVICESERVICE_EXCEPTION;
        }
        return STRINGSERVICESERVICE_WSDL_LOCATION;
    }

}
