
package webservice;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StringService", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StringService {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "linkStr", targetNamespace = "http://webservice/", className = "webservice.LinkStr")
    @ResponseWrapper(localName = "linkStrResponse", targetNamespace = "http://webservice/", className = "webservice.LinkStrResponse")
    @Action(input = "http://webservice/StringService/linkStrRequest", output = "http://webservice/StringService/linkStrResponse")
    public String linkStr();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compareStr", targetNamespace = "http://webservice/", className = "webservice.CompareStr")
    @ResponseWrapper(localName = "compareStrResponse", targetNamespace = "http://webservice/", className = "webservice.CompareStrResponse")
    @Action(input = "http://webservice/StringService/compareStrRequest", output = "http://webservice/StringService/compareStrResponse")
    public String compareStr();

}
