
package buptsse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "StringOperationDelegate", targetNamespace = "http://buptsse/")
public interface StringOperationDelegate {

	/**
	 * 
	 * @param str1
	 * @param str2
	 * @return returns java.lang.Boolean
	 */
	@WebMethod(operationName = "CompareString")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "CompareString", targetNamespace = "http://buptsse/", className = "buptsse.CompareString")
	@ResponseWrapper(localName = "CompareStringResponse", targetNamespace = "http://buptsse/", className = "buptsse.CompareStringResponse")
	public Boolean compareString(@WebParam(name = "str1", targetNamespace = "") String str1,
			@WebParam(name = "str2", targetNamespace = "") String str2);

	/**
	 * 
	 * @param str1
	 * @param str2
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "AddString")
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "AddString", targetNamespace = "http://buptsse/", className = "buptsse.AddString")
	@ResponseWrapper(localName = "AddStringResponse", targetNamespace = "http://buptsse/", className = "buptsse.AddStringResponse")
	public String addString(@WebParam(name = "str1", targetNamespace = "") String str1,
			@WebParam(name = "str2", targetNamespace = "") String str2);

}
